### PR TITLE
Add Party System

### PR DESCRIPTION
**Pull request by felipecastagnarodecarvalho**
I accept any suggestion if refactor is needed.

### CODE REVIEW

**Comment by felipecastagnarodecarvalho** [comment]
Working and tested features:
  - Invite member
  - Expel member
  - Exp distribution
  - Item distribution
  
  Missing/Bugged features:
  - Once the player leave the new leader is not set
  - The party is not being sync correct and once the player logins it doesn't show the party properly
  - Guild Features not tested yet

**Comment by felipecastagnarodecarvalho** [comment]
TODO:
 - Once a character is deleted make it to leave the party (clean up the data as well)

**Comment by exectails** [comment]
I see that this PR is still marked as a draft, could you let me know what its current status is?

**Comment by felipecastagnarodecarvalho** [comment]
This PR is very old but I think I could work on it after finishing sadhu skills.

**Pull request closed without merging**
