### PR TITLE
Adding Wugushi Skills

### PR DESCRIPTION
**Pull request by felipecastagnarodecarvalho**
Wugushi Skills:
- Wugong Gu
- Zhendu
- Latent Venom
- Golden Frog
- WideMiasma

### CODE REVIEW

**Comment by felipecastagnarodecarvalho** [comment]
Missing:
 - Golden Frog skill effect not being displayed
  - Throw Pot skill effect not being displayed

**Comment by exectails** [comment]
Thank you for the PR, but I see you're listing missing effects. Before I review the actual changes, what's the problem with the effects? I'd prefer not to merge half-implemented skills, since we'd run the risk of forgetting about finishing them.

**Comment by felipecastagnarodecarvalho** [comment]
Yeah the idea is to fully display the effects before you try to merge it.
So it was being displayed before I updated the client.
And for some reason now it doesn't show up.
I am gonna try again tho.

**Comment by exectails** [comment]
Updates often times change the packet strings and their ids, which also affects the effects that use them. Could that be the issue?

**Comment by felipecastagnarodecarvalho** [comment]
I could be it! How can we test it out?

**Comment by exectails** [comment]
Update your client and see if that fixes it^^

**Comment by felipecastagnarodecarvalho** [comment]
I did but did not fix it properly.
Do you think the packetstrings.txt file could be outdated/old ?

**Comment by felipecastagnarodecarvalho** [comment]
this was fixed by using exclusive the steam client for tests

**Comment by felipecastagnarodecarvalho** [comment]
Current issues/bugs:
 - Can't display two effects at the same time (based on the skill_59 function) - If you use PoisonPot the GoldenFrog effect will not be showed.

**Comment by felipecastagnarodecarvalho** [comment]
Closing since we are making another PR with this content

**Pull request closed without merging**
