### PR TITLE
this simple test selfskill

### PR DESCRIPTION
**Pull request by kawisin**
please review i think is not perfect.
some skill call in melee ground
and all buff will call in folder buff only

### CODE REVIEW

**Comment by exectails** [comment]
Hey. I'm sorry I didn't get to reviewing your PR some time in the last... \*cough* one-and-a-half years... Thank you for trying to contribute though!^^ Would you still be up to working on this?

**Comment by kawisin** [comment]
Yeah i can . what about update

ส่งจาก iPhone ของฉัน

> เมื่อ 17 พ.ค. 2566 เวลา 14:28 เขียนโดย exec ***@***.***>:
> 
> Hey. I'm sorry I didn't get to reviewing your PR some time in the last... *cough* one-and-a-half years... Thank you for trying to contribute though!^^ Would you still be up to working on this?

**Comment by exectails** [comment]
I'm currently in the process of rewriting some parts of the server, which will require a few updates to your code. My changes will be merged into master soon, at which point you may update your pull request to work with the latest version of Melia. Afterwards I would take a closer look at your changes.

**Comment by exectails** [comment]
My changes were recently merged into master, and as was to be expected, this caused a couple conflicts with your branch because I moved quite a few things around. If you'd like, you can now update your pull request, or perhaps recreate it if that's easier, to make it work with the latest version.

**Comment by kawisin** [comment]
It's nothing, it's very old and can be reworked easier. and will join soon .i see private server in thailand not sure where it came

**Comment by exectails** [comment]
I'll close this PR for now since several of the skills have been added and it will need an overhaul anyway.

**Pull request closed without merging**
